#!/bin/sh
set -e

cat data/$1/$2.json | 
    jq -c '.result.hits.hit[] | {title: .info.title, authors: ([.info.authors.author | if type == "array" then .[] else . end | select(.text != null) | .text] | join(", ")), url: .info.ee, venue: .info.venue, year: .info.year}' | 
    rg -i "$3" | 
    jq -r '"\(.title)\n\(.authors). \(.venue) \(.year).\n\(.url)\n"'
